sudo: true
language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - rm -fr $HOME/android-ndk-r16b
  - curl -L http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
  - unzip -oq -d $HOME android-ndk-r16b-linux-x86_64.zip
  - rm android-ndk-r16b-linux-x86_64.zip
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r16b
