name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: malinskiy/action-android/install-sdk@release/0.0.5
    - run: $ANDROID_HOME/tools/bin/sdkmanager 'ndk;20.0.5594570'
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
