name: Android translation validation

on:
  # push: # Only for test
    # paths:
    #   - 'app/src/main/res/values*/string*.xml'
  pull_request:
    branches:
      - master
    paths:
      - 'app/src/main/res/values*/string*.xml'

jobs:
  build:
    name: Validate translations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # with: # Remove for PR
        #   fetch-depth: 0 

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.9 

      - name: Validate locale files
        id: validation
        run: |
          cd ${GITHUB_WORKSPACE}
          java .github/workflows/AndroidLocaleChecker.java ${{ steps.changed-files.outputs.all_modified_files }}

      - name: Commit patch
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.validation.outputs.patch_applied == 'true'
